[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "gitgram"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "flask==2.2.5",
    "jinja2==3.0.3",
    "requests==2.31.0",
    "urllib3==2.0.7",
    "six==1.16.0",
    "python-telegram-bot==13.15"
]
